// Tiny markdown renderer for our controlled blog posts (generated by
// scripts/generate_blog_ko.py). NOT a general-purpose markdown engine —
// only handles the subset our generator emits:
//   ## heading       → <h2>
//   ### heading      → <h3>
//   - item           → <li>
//   1. item          → <li> (ordered)
//   > quote          → <blockquote>
//   **bold**         → <strong>
//   *italic*         → <em>
//   [text](url)      → <a>  (internal /ko/... gets <Link>)
//   blank line       → paragraph break
//
// Why custom: react-markdown adds ~30kB; we ship 200+ static blog pages.

import Link from "next/link";
import { Fragment } from "react";

function inline(text: string): React.ReactNode[] {
  // Process inline tokens: **bold**, *italic*, [link](url)
  const nodes: React.ReactNode[] = [];
  let remaining = text;
  let key = 0;
  const regex = /\*\*([^*]+)\*\*|\*([^*]+)\*|\[([^\]]+)\]\(([^)]+)\)/;
  while (remaining) {
    const m = regex.exec(remaining);
    if (!m) {
      nodes.push(<Fragment key={key++}>{remaining}</Fragment>);
      break;
    }
    if (m.index > 0) {
      nodes.push(<Fragment key={key++}>{remaining.slice(0, m.index)}</Fragment>);
    }
    if (m[1]) {
      nodes.push(<strong key={key++}>{m[1]}</strong>);
    } else if (m[2]) {
      nodes.push(<em key={key++}>{m[2]}</em>);
    } else if (m[3] && m[4]) {
      const isInternal = m[4].startsWith("/") || m[4].startsWith("#");
      if (isInternal) {
        nodes.push(
          <Link
            key={key++}
            href={m[4]}
            className="text-emerald-700 underline-offset-2 hover:underline dark:text-emerald-400"
          >
            {m[3]}
          </Link>,
        );
      } else {
        nodes.push(
          <a
            key={key++}
            href={m[4]}
            target="_blank"
            rel="noopener nofollow"
            className="text-emerald-700 underline-offset-2 hover:underline dark:text-emerald-400"
          >
            {m[3]}
          </a>,
        );
      }
    }
    remaining = remaining.slice(m.index + m[0].length);
  }
  return nodes;
}

export default function BlogMarkdown({ source }: { source: string }) {
  const lines = source.split("\n");
  const blocks: React.ReactNode[] = [];
  let para: string[] = [];
  let listItems: string[] = [];
  let listOrdered = false;
  let key = 0;

  const flushPara = () => {
    if (para.length === 0) return;
    blocks.push(
      <p key={key++} className="mt-4 text-base leading-relaxed text-ink-800 dark:text-ink-200">
        {inline(para.join(" "))}
      </p>,
    );
    para = [];
  };
  const flushList = () => {
    if (listItems.length === 0) return;
    const Tag = listOrdered ? "ol" : "ul";
    blocks.push(
      <Tag
        key={key++}
        className={`mt-4 ml-5 space-y-2 text-base leading-relaxed text-ink-800 dark:text-ink-200 ${
          listOrdered ? "list-decimal" : "list-disc"
        }`}
      >
        {listItems.map((it, i) => (
          <li key={i}>{inline(it)}</li>
        ))}
      </Tag>,
    );
    listItems = [];
  };

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line === "") {
      flushPara();
      flushList();
      continue;
    }
    if (line.startsWith("## ")) {
      flushPara();
      flushList();
      blocks.push(
        <h2 key={key++} className="mt-10 text-2xl font-black tracking-tight">
          {inline(line.slice(3))}
        </h2>,
      );
      continue;
    }
    if (line.startsWith("### ")) {
      flushPara();
      flushList();
      blocks.push(
        <h3 key={key++} className="mt-6 text-lg font-bold">
          {inline(line.slice(4))}
        </h3>,
      );
      continue;
    }
    if (line.startsWith("> ")) {
      flushPara();
      flushList();
      blocks.push(
        <blockquote
          key={key++}
          className="mt-3 border-l-4 border-emerald-400 bg-emerald-50/40 px-4 py-2 text-sm italic text-ink-700 dark:bg-emerald-950/20 dark:text-ink-300"
        >
          {inline(line.slice(2))}
        </blockquote>,
      );
      continue;
    }
    const olMatch = /^\d+\.\s+(.*)$/.exec(line);
    if (olMatch) {
      flushPara();
      if (!listOrdered && listItems.length > 0) flushList();
      listOrdered = true;
      listItems.push(olMatch[1]);
      continue;
    }
    if (line.startsWith("- ") || line.startsWith("  > ")) {
      // Treat indented quote ("  > ...") inside a list item as a sub-quote
      // (our place_card_md emits these for review snippets) — render inline
      // for compactness.
      if (line.startsWith("- ")) {
        flushPara();
        if (listOrdered && listItems.length > 0) flushList();
        listOrdered = false;
        listItems.push(line.slice(2));
        continue;
      }
      // sub-quote — append to last list item if any
      if (listItems.length > 0) {
        listItems[listItems.length - 1] += "\n\n> " + line.slice(4);
      }
      continue;
    }
    // Fallback: paragraph line
    para.push(line);
  }
  flushPara();
  flushList();

  return <>{blocks}</>;
}
