import type { Lang } from "./types";
import uiI18n from "../public/data/ui_i18n.json";

// Machine-translated UI strings for locales not hand-filled in the T dictionary
// below (generated by scripts/translate_ui.mjs). Shape: { [key]: { [lang]: str } }.
// Merged in t() with precedence: curated T[key][lang] > this sidecar > English.
const UI_I18N = uiI18n as Record<string, Partial<Record<Lang, string>>>;

// `id` (Indonesian) is fully scaffolded and translated (UI sidecar ui_i18n.json
// + FAQ corpus faq_i18n.json), so it's active: route generation, sitemap, and
// hreflang now include it. The FAQ indexing gate (isFaqTranslated) keeps any
// untranslated FAQ noindexed per locale.
export const SUPPORTED_LANGS: Lang[] = ["en", "ko", "th", "zh", "ja", "ar", "id", "vi"];
export const DEFAULT_LANG: Lang = "en";

export const SITE = {
  origin: "https://verifiedthai.com",
  name: "Verified Thai",
  tagline: {
    en: "Thailand's independent business directory. Verified by 6 sources. No paid promotion.",
    ko: "광고 거품 없는 태국 비즈니스 디렉토리. 6개 소스에서 교차 검증.",
    th: "ไดเรกทอรีธุรกิจในไทย ตรวจสอบจาก 6 แหล่ง ไม่มีโปรโมชันที่จ่ายเงิน",
    zh: "泰国独立商家指南 — 来自6个独立来源的验证，不含付费推广。",
    ja: "タイのビジネス独立ガイド — 6つの独立情報源で検証、有料宣伝なし。",
    ar: "الدليل المستقل لأعمال تايلاند — تم التحقق من 6 مصادر، بدون ترويج مدفوع.",
    id: "Direktori bisnis independen Thailand. Diverifikasi dari 6 sumber. Tanpa promosi berbayar.",
    vi: "Danh bạ doanh nghiệp độc lập của Thái Lan. Được xác minh từ 6 nguồn. Không quảng cáo trả phí.",
  },
} as const;

export const T = {
  // navigation
  nav_explore: { en: "Explore", ko: "탐색", th: "สำรวจ", zh: "探索", ja: "探索", ar: "استكشف" },
  nav_about: { en: "About", ko: "소개", th: "เกี่ยวกับ", zh: "关于", ja: "概要", ar: "حول" },

  // landing hero
  hero_title: {
    en: "Verified Thailand. No paid hype.",
    ko: "검증된 태국. 광고 거품 X.",
    th: "ไทยแลนด์ที่ตรวจสอบแล้ว ไม่มีโฆษณาเกินจริง",
    zh: "可信泰国，无虚假宣传。",
    ja: "信頼できるタイ。誇大広告なし。",
    ar: "تايلاند الموثقة. بدون دعاية مدفوعة.",
  },
  hero_subtitle: {
    en: "Camps. Studios. Retreats. Cooking schools. Dive shops. Spas. Workspaces. Independently scored across 6 sources.",
    ko: "캠프, 스튜디오, 리트릿, 요리학교, 다이빙샵, 스파, 워크스페이스 — 6개 독립 소스로 점수화.",
    th: "ค่าย สตูดิโอ รีทรีต โรงเรียนทำอาหาร ร้านดำน้ำ สปา และพื้นที่ทำงาน — ให้คะแนนจาก 6 แหล่งอิสระ",
    zh: "训练营、工作室、度假村、烹饪学校、潜水店、水疗中心和共享空间 — 来自6个独立来源的评分。",
    ja: "キャンプ、スタジオ、リトリート、料理学校、ダイビングショップ、スパ、コワーキング — 6つの情報源で独自スコア化。",
    ar: "معسكرات. استوديوهات. منتجعات. مدارس طبخ. مراكز غوص. سبا. مساحات عمل. مقيّمة من 6 مصادر مستقلة.",
  },

  // audience clarifier — appears below hero subtitle
  for_audience: {
    en: "🧳 Tourists  ·  🏠 Expats  ·  🇹🇭 Residents",
    ko: "🧳 여행자  ·  🏠 거주 외국인  ·  🇹🇭 현지인",
    th: "🧳 นักท่องเที่ยว  ·  🏠 ชาวต่างชาติพำนัก  ·  🇹🇭 คนไทย",
    zh: "🧳 游客  ·  🏠 外籍居民  ·  🇹🇭 本地居民",
    ja: "🧳 観光客  ·  🏠 在住外国人  ·  🇹🇭 タイ在住者",
    ar: "🧳 سياح  ·  🏠 مقيمون أجانب  ·  🇹🇭 المقيمون المحليون",
  },

  popular_picks: {
    en: "Popular picks",
    ko: "인기 검색",
    th: "ค้นหายอดนิยม",
    zh: "热门精选",
    ja: "人気の選択",
    ar: "الأكثر شعبية",
  },

  // multi-source pitch
  sources_pitch: {
    en: "Each place is cross-checked against Google · Reddit · Naver · Pantip · YouTube · Bookimed",
    ko: "각 장소는 구글 · Reddit · 네이버 · Pantip · 유튜브 · Bookimed에서 교차 검증",
    th: "แต่ละสถานที่ตรวจสอบจาก Google · Reddit · Naver · Pantip · YouTube · Bookimed",
    zh: "每个地点都经过 Google · Reddit · Naver · Pantip · YouTube · Bookimed 交叉验证",
    ja: "各スポットは Google · Reddit · Naver · Pantip · YouTube · Bookimed で相互検証",
    ar: "كل مكان تم التحقق منه عبر Google و Reddit و Naver و Pantip و YouTube و Bookimed",
  },

  // category section
  browse_categories: { en: "Browse categories", ko: "카테고리 둘러보기", th: "เรียกดูหมวดหมู่", zh: "浏览分类", ja: "カテゴリーを見る", ar: "تصفح الفئات" },
  see_all: { en: "See all", ko: "전체 보기", th: "ดูทั้งหมด", zh: "查看全部", ja: "すべて見る", ar: "عرض الكل" },
  places_count: { en: "places", ko: "곳", th: "แห่ง", zh: "处", ja: "件", ar: "أماكن" },

  // directory
  trust_score: { en: "Trust Score", ko: "신뢰 점수", th: "คะแนนความน่าเชื่อถือ", zh: "信任分数", ja: "信頼スコア", ar: "درجة الثقة" },
  filter_out_viral: {
    en: "Hide low-corroboration listings",
    ko: "교차검증 낮은 곳 숨기기",
    th: "ซ่อนรายการที่ยืนยันข้ามแหล่งได้น้อย",
    zh: "隐藏交叉验证较低的条目",
    ja: "裏付けの少ない掲載を非表示",
    ar: "إخفاء القوائم ذات التحقق المنخفض",
  },
  sort_by: { en: "Sort by", ko: "정렬", th: "เรียงตาม", zh: "排序", ja: "並び替え", ar: "ترتيب" },
  sort_trust: { en: "Trust Score", ko: "신뢰 점수", th: "คะแนน", zh: "信任分数", ja: "信頼スコア", ar: "درجة الثقة" },
  sort_reviews: { en: "Most reviewed", ko: "리뷰 많은 순", th: "รีวิวมากที่สุด", zh: "评论最多", ja: "レビュー数", ar: "الأكثر تقييمًا" },
  sort_rating: { en: "Highest rated", ko: "별점 높은 순", th: "คะแนนสูงสุด", zh: "评分最高", ja: "評価順", ar: "الأعلى تقييمًا" },
  search_ph: {
    en: "Search places, cities, categories…",
    ko: "장소·도시·카테고리 검색…",
    th: "ค้นหาสถานที่ เมือง หมวดหมู่…",
    zh: "搜索场所、城市、分类…",
    ja: "場所・都市・カテゴリーを検索…",
    ar: "ابحث عن أماكن، مدن، فئات…",
  },

  // filters
  filter_beginner: { en: "Beginner-friendly", ko: "초보 친화", th: "เหมาะกับมือใหม่", zh: "适合初学者", ja: "初心者向け", ar: "مناسب للمبتدئين" },
  filter_korean_friendly: { en: "Korean-friendly", ko: "한국어 가능", th: "รองรับเกาหลี", zh: "韩语友好", ja: "韓国語対応", ar: "يدعم الكورية" },
  filter_24h: { en: "Open 24h", ko: "24시간 운영", th: "เปิด 24 ชม.", zh: "24小时营业", ja: "24時間営業", ar: "مفتوح 24 ساعة" },
  filter_established: { en: "Established (5y+)", ko: "5년+ 운영", th: "ดำเนินกิจการ 5 ปี+", zh: "营业 5 年以上", ja: "5年以上の老舗", ar: "قائم منذ 5 سنوات+" },
  filter_active: { en: "Active recently", ko: "최근 활발", th: "เปิดให้บริการล่าสุด", zh: "近期活跃", ja: "最近も営業中", ar: "نشط مؤخراً" },
  price_band: { en: "Price", ko: "가격대", th: "ราคา", zh: "价格", ja: "価格", ar: "السعر" },
  price_budget: { en: "Budget", ko: "저렴", th: "ประหยัด", zh: "经济", ja: "格安", ar: "اقتصادي" },
  price_mid: { en: "Mid", ko: "중간", th: "ปานกลาง", zh: "中等", ja: "普通", ar: "متوسط" },
  price_premium: { en: "Premium", ko: "프리미엄", th: "พรีเมียม", zh: "高端", ja: "プレミアム", ar: "متميز" },
  price_luxury: { en: "Luxury", ko: "럭셔리", th: "หรูหรา", zh: "奢华", ja: "ラグジュアリー", ar: "فاخر" },

  // place detail
  patient_voices: { en: "What people actually said", ko: "진짜 사람들의 후기", th: "ผู้คนพูดว่ายังไง", zh: "真实评价", ja: "実際の声", ar: "ماذا قال الناس فعلاً" },
  faq: { en: "Frequently asked", ko: "자주 묻는 질문", th: "คำถามที่พบบ่อย", zh: "常见问题", ja: "よくある質問", ar: "أسئلة شائعة" },
  hours: { en: "Hours", ko: "운영시간", th: "เวลาทำการ", zh: "营业时间", ja: "営業時間", ar: "ساعات العمل" },
  price_range: { en: "Price range", ko: "가격대", th: "ช่วงราคา", zh: "价格范围", ja: "価格帯", ar: "نطاق السعر" },

  // CTAs
  cta_book_klook: { en: "Book on Klook", ko: "Klook 예약", th: "จองบน Klook", zh: "Klook 预订", ja: "Klookで予約", ar: "احجز عبر Klook" },
  cta_book_viator: { en: "Book on Viator", ko: "Viator 예약", th: "จองบน Viator", zh: "Viator 预订", ja: "Viatorで予約", ar: "احجز عبر Viator" },
  cta_book_gyg: { en: "Book on GetYourGuide", ko: "GetYourGuide 예약", th: "จองบน GetYourGuide", zh: "GetYourGuide 预订", ja: "GetYourGuideで予約", ar: "احجز عبر GetYourGuide" },
  cta_book_agoda: { en: "Find on Agoda", ko: "Agoda 검색", th: "หาบน Agoda", zh: "Agoda 查找", ja: "Agodaで探す", ar: "ابحث على Agoda" },
  cta_view_map: { en: "View on Google Maps", ko: "구글 맵에서 보기", th: "ดูบน Google Maps", zh: "Google 地图查看", ja: "Google マップで見る", ar: "عرض على خرائط جوجل" },

  // sources (badges)
  source_google: { en: "Google", ko: "구글", th: "Google", zh: "Google", ja: "Google", ar: "جوجل" },
  source_reddit: { en: "Reddit", ko: "Reddit", th: "Reddit", zh: "Reddit", ja: "Reddit", ar: "Reddit" },
  source_naver: { en: "Naver", ko: "네이버", th: "Naver", zh: "Naver", ja: "Naver", ar: "نيفر" },
  source_pantip: { en: "Pantip", ko: "Pantip", th: "Pantip", zh: "Pantip", ja: "Pantip", ar: "Pantip" },
  source_youtube: { en: "YouTube", ko: "유튜브", th: "YouTube", zh: "YouTube", ja: "YouTube", ar: "يوتيوب" },
  source_bookimed: { en: "Bookimed", ko: "Bookimed", th: "Bookimed", zh: "Bookimed", ja: "Bookimed", ar: "Bookimed" },
  source_website: { en: "Official site", ko: "공식 사이트", th: "เว็บไซต์ทางการ", zh: "官网", ja: "公式サイト", ar: "الموقع الرسمي" },

  // category page status
  coming_soon: { en: "Coming soon", ko: "준비 중", th: "เร็วๆ นี้", zh: "即将推出", ja: "近日公開", ar: "قريبًا" },
  coming_soon_msg: {
    en: "This category is currently being verified across our 6 sources. Check back soon.",
    ko: "이 카테고리는 6개 소스에서 현재 검증 중입니다. 곧 다시 확인해주세요.",
    th: "หมวดหมู่นี้กำลังตรวจสอบจาก 6 แหล่ง โปรดกลับมาดูใหม่",
    zh: "此分类正在通过6个来源进行验证，敬请期待。",
    ja: "このカテゴリーは現在6つの情報源で検証中です。もう少しお待ちください。",
    ar: "يتم التحقق من هذه الفئة حاليًا عبر 6 مصادر. عد قريبًا.",
  },
  no_matches: { en: "No matches", ko: "결과 없음", th: "ไม่พบรายการ", zh: "没有匹配", ja: "該当なし", ar: "لا توجد نتائج" },
  try_remove_filters: {
    en: "Try removing some filters.",
    ko: "필터를 일부 해제해 보세요.",
    th: "ลองลบตัวกรองบางตัวออก",
    zh: "尝试移除一些筛选条件。",
    ja: "フィルターをいくつか外してみてください。",
    ar: "حاول إزالة بعض المرشحات.",
  },
  reset: { en: "Reset", ko: "초기화", th: "ล้าง", zh: "重置", ja: "リセット", ar: "إعادة تعيين" },
  all_label: { en: "All", ko: "전체", th: "ทั้งหมด", zh: "全部", ja: "すべて", ar: "الكل" },

  // landing
  top_picks: { en: "Top picks", ko: "추천", th: "แนะนำ", zh: "精选", ja: "おすすめ", ar: "الاختيارات" },
  score_pitch_title: {
    en: "How we score every place",
    ko: "모든 장소를 어떻게 점수화하는지",
    th: "เราให้คะแนนแต่ละสถานที่อย่างไร",
    zh: "我们如何为每个地点评分",
    ja: "各スポットのスコア算出方法",
    ar: "كيف نقيم كل مكان",
  },
  score_pitch_blurb: {
    en: "Every Trust Score combines independent signals. No place can buy a higher rank — the formula is public.",
    ko: "신뢰 점수는 독립적인 신호들을 결합합니다. 어떤 장소도 순위를 살 수 없습니다 — 공식은 공개되어 있습니다.",
    th: "คะแนนความน่าเชื่อถือทุกคะแนนรวมจากสัญญาณอิสระ ไม่มีสถานที่ใดซื้ออันดับได้ — สูตรเปิดเผยต่อสาธารณะ",
    zh: "每个信任分数综合独立信号。没有任何地方可以购买更高排名 — 公式是公开的。",
    ja: "信頼スコアは独立した信号を組み合わせます。順位は買えません — 算出式は公開されています。",
    ar: "كل درجة ثقة تجمع إشارات مستقلة. لا يمكن لأي مكان شراء ترتيب أعلى — الصيغة عامة.",
  },

  // place detail
  book_or_inquire: { en: "Book / Inquire", ko: "예약 / 문의", th: "จอง / สอบถาม", zh: "预订 / 咨询", ja: "予約 / お問い合わせ", ar: "احجز / استفسر" },
  affiliate_disclaimer: {
    en: "Affiliate links — we may earn a commission. Trust Score is computed before any commercial relationship.",
    ko: "제휴 링크 — 수수료를 받을 수 있습니다. 신뢰 점수는 상업 관계와 무관하게 산정됩니다.",
    th: "ลิงก์พาร์ทเนอร์ — เราอาจได้รับค่าคอมมิชชั่น คะแนนคำนวณก่อนความสัมพันธ์ทางการค้า",
    zh: "联盟链接 — 我们可能赚取佣金。信任分数在任何商业关系之前计算。",
    ja: "アフィリエイトリンク — 手数料を得る場合があります。信頼スコアは商業関係の前に計算されます。",
    ar: "روابط تابعة — قد نحصل على عمولة. درجة الثقة تحسب قبل أي علاقة تجارية.",
  },
  photos_label: { en: "Photos", ko: "사진", th: "ภาพถ่าย", zh: "照片", ja: "写真", ar: "صور" },
  community_discussions: {
    en: "Community discussions",
    ko: "커뮤니티 토론",
    th: "การสนทนาในชุมชน",
    zh: "社区讨论",
    ja: "コミュニティの議論",
    ar: "نقاشات المجتمع",
  },
  community_blurb: {
    en: "Unfiltered conversations from Reddit, Pantip (TH), and Naver (KR) — independent perspectives that complement Google reviews.",
    ko: "Reddit, Pantip(태국), Naver(한국)의 필터링되지 않은 대화 — 구글 리뷰를 보완하는 독립적인 시각.",
    th: "บทสนทนาที่ไม่กรองจาก Reddit, Pantip และ Naver — มุมมองอิสระที่เสริมรีวิว Google",
    zh: "来自 Reddit、Pantip（泰国）和 Naver（韩国）的未过滤对话 — 补充 Google 评论的独立视角。",
    ja: "Reddit、Pantip（タイ）、Naver（韓国）の未加工の会話 — Googleレビューを補完する独立した視点。",
    ar: "محادثات غير مفلترة من Reddit و Pantip و Naver — وجهات نظر مستقلة تكمل تقييمات Google.",
  },
  mentions_in_community: {
    en: "Mentions in community discussions",
    ko: "커뮤니티에서 언급된 곳",
    th: "การกล่าวถึงในชุมชน",
    zh: "社区讨论中的提及",
    ja: "コミュニティでの言及",
    ar: "ذكر في نقاشات المجتمع",
  },
  mentions_blurb: {
    en: "Threads where this place's name appears. Independent voices, not curated reviews.",
    ko: "이 장소가 언급된 스레드들. 큐레이션된 리뷰가 아닌 독립적인 목소리.",
    th: "เธรดที่กล่าวถึงสถานที่นี้ เสียงอิสระที่ไม่ผ่านการคัดสรร",
    zh: "提及此地的讨论。独立声音，非筛选评论。",
    ja: "この場所が登場するスレッド。キュレーションされていない独立した声。",
    ar: "مواضيع تظهر فيها اسم هذا المكان. أصوات مستقلة، ليست تقييمات منسقة.",
  },
  contact_links: {
    en: "Contact & links",
    ko: "연락처 & 링크",
    th: "ติดต่อและลิงก์",
    zh: "联系方式与链接",
    ja: "連絡先・リンク",
    ar: "اتصل والروابط",
  },
  address_label: { en: "Address", ko: "주소", th: "ที่อยู่", zh: "地址", ja: "住所", ar: "العنوان" },
  phone_label: { en: "Phone", ko: "전화", th: "โทรศัพท์", zh: "电话", ja: "電話", ar: "هاتف" },
  website_label: { en: "Website", ko: "웹사이트", th: "เว็บไซต์", zh: "网站", ja: "ウェブサイト", ar: "موقع" },
  back_to_all: {
    en: "All categories",
    ko: "전체 카테고리",
    th: "หมวดหมู่ทั้งหมด",
    zh: "全部分类",
    ja: "全カテゴリー",
    ar: "كل الفئات",
  },
  low_signal_warn: {
    en: "Limited independent signal: a high rating from relatively few reviews. We haven't been able to corroborate it across our other sources yet — we suggest checking for yourself.",
    ko: "독립 신호 부족: 적은 리뷰로 높은 평점. 아직 다른 소스로 교차 확인이 안 됐어요 — 직접 확인을 권장합니다.",
    th: "สัญญาณอิสระจำกัด: คะแนนสูงจากรีวิวค่อนข้างน้อย เรายังยืนยันข้ามแหล่งอื่นไม่ได้ — แนะนำให้ตรวจสอบด้วยตนเอง",
    zh: "独立信号有限：评分较高但评论较少。我们尚未能在其他来源中交叉验证 — 建议您自行核实。",
    ja: "独立した情報が限定的：少ないレビューでの高評価です。他の情報源ではまだ裏付けが取れていません — ご自身での確認をおすすめします。",
    ar: "إشارة مستقلة محدودة: تقييم عالٍ من عدد قليل من المراجعات. لم نتمكن بعد من تأكيده عبر مصادرنا الأخرى — ننصح بالتحقق بنفسك.",
  },
  bookable_label: { en: "Bookable", ko: "예약 가능", th: "จองได้", zh: "可预订", ja: "予約可", ar: "متاح للحجز" },
  threads_scanned: { en: "threads scanned", ko: "스레드 스캔됨", th: "เธรดที่สแกน", zh: "条讨论已扫描", ja: "スレッドをスキャン", ar: "موضوع تم مسحه" },
  matches_of: { en: "matches of", ko: "/", th: "จาก", zh: "/", ja: "/", ar: "من" },

  // footer
  footer_blurb: {
    en: "Verified Thai is an independent directory. Affiliate commissions from booking partners support the site but never influence Trust Scores.",
    ko: "Verified Thai는 독립 디렉토리입니다. 예약 파트너로부터 수수료를 받지만 신뢰 점수에 영향을 주지 않습니다.",
    th: "Verified Thai เป็นไดเรกทอรีอิสระ ค่าคอมมิชชั่นจากพาร์ทเนอร์ไม่ส่งผลต่อคะแนน",
    zh: "Verified Thai 是独立目录。来自预订合作伙伴的佣金支持网站运营，但不影响信任分数。",
    ja: "Verified Thaiは独立したディレクトリです。提携先からの手数料はサイト運営を支えますが、信頼スコアには影響しません。",
    ar: "Verified Thai دليل مستقل. عمولات الشركاء تدعم الموقع لكنها لا تؤثر على درجات الثقة.",
  },
  // place-detail highlights ("이 곳 한눈에")
  hl_title: { en: "At a glance", ko: "이 곳 한눈에", th: "ภาพรวม", zh: "一览", ja: "ひと目で", ar: "لمحة سريعة" },
  hl_since: { en: "Since {y}", ko: "{y}년부터", th: "ตั้งแต่ {y}", zh: "{y}年起", ja: "{y}年から", ar: "منذ {y}" },
  hl_years: { en: "{n}y running", ko: "{n}년차", th: "{n} ปี", zh: "经营{n}年", ja: "{n}年目", ar: "{n} سنوات" },
  hl_reviews: { en: "{n} reviews", ko: "리뷰 {n}개", th: "{n} รีวิว", zh: "{n}条评价", ja: "{n}件", ar: "{n} تقييم" },
  hl_lang_ok: { en: "English-friendly", ko: "한국어 가능", th: "พูดไทยได้", zh: "中文友好", ja: "日本語対応", ar: "نتحدث العربية" },
  hl_price_from: { en: "from ฿{n}", ko: "฿{n}~", th: "เริ่ม ฿{n}", zh: "฿{n}起", ja: "฿{n}〜", ar: "من ฿{n}" },
  hl_price_on_inquiry: { en: "Price on inquiry", ko: "가격: 문의 시 안내", th: "ราคาสอบถาม", zh: "价格请咨询", ja: "価格はお問い合わせ", ar: "السعر عند الطلب" },
  // place-detail smart CTA
  cta_check_booking: { en: "Check availability & price", ko: "예약·가격 확인", th: "เช็คคิวและราคา", zh: "查看可订与价格", ja: "空き状況・料金を確認", ar: "تحقق من التوفر والسعر" },
  cta_inquiry_main: { en: "Send inquiry · reply within 24h", ko: "지금 문의 · 보통 24시간 내 답변", th: "ส่งคำถาม · ตอบใน 24 ชม.", zh: "立即咨询 · 24小时内回复", ja: "問い合わせ · 24時間以内に返信", ar: "أرسل استفسارًا · رد خلال 24 ساعة" },
  cta_inquiry_short: { en: "Inquire", ko: "문의하기", th: "สอบถาม", zh: "咨询", ja: "問い合わせ", ar: "استفسر" },
  social_more: { en: "More reviews & mentions", ko: "더 많은 후기·언급 보기", th: "ดูรีวิว/การกล่าวถึงเพิ่มเติม", zh: "更多评价与提及", ja: "他のレビュー・言及を見る", ar: "المزيد من التقييمات والإشارات" },
  recently_viewed: { en: "Recently viewed", ko: "최근 본 곳", th: "ดูล่าสุด", zh: "最近浏览", ja: "最近見た場所", ar: "شوهدت مؤخرًا", id: "Baru dilihat", vi: "Đã xem gần đây" },

  // ── place-detail dynamic FAQ (drives visible accordion + FAQPage/QAPage JSON-LD).
  // These are the AEO payload — they must be native, not English shells. {name},
  // {addr}, {price}, {count}, {rating}, {langs}, {phone} are filled with tf().
  faq_section: { en: "Frequently asked questions", ko: "자주 묻는 질문", th: "คำถามที่พบบ่อย", zh: "常见问题", ja: "よくある質問", ar: "الأسئلة الشائعة" },
  nav_faq: { en: "FAQ", ko: "FAQ", th: "FAQ", zh: "常见问题", ja: "FAQ", ar: "الأسئلة الشائعة", id: "FAQ" },
  faq_related: { en: "Related questions", ko: "관련 질문", th: "คำถามที่เกี่ยวข้อง", zh: "相关问题", ja: "関連する質問", ar: "أسئلة ذات صلة", id: "Pertanyaan terkait" },
  faq_all_link: { en: "All FAQs", ko: "전체 FAQ", th: "คำถามทั้งหมด", zh: "全部问题", ja: "すべてのFAQ", ar: "كل الأسئلة", id: "Semua FAQ" },
  pf_loc_q: { en: "Where is {name} located?", ko: "{name} 위치가 어디인가요?", th: "{name} ตั้งอยู่ที่ไหน?", zh: "{name} 在哪里？", ja: "{name}はどこにありますか？", ar: "أين يقع {name}؟" },
  pf_loc_a: { en: "{addr}.", ko: "{addr}.", th: "{addr}", zh: "{addr}。", ja: "{addr}。", ar: "{addr}." },
  pf_loc_maps: { en: " Open in Google Maps: {url}", ko: " 구글 지도에서 열기: {url}", th: " เปิดใน Google Maps: {url}", zh: " 在 Google 地图中打开：{url}", ja: " Google マップで開く: {url}", ar: " افتح في خرائط جوجل: {url}" },
  pf_book_q: { en: "How do I book or contact {name}?", ko: "{name} 예약·문의는 어떻게 하나요?", th: "จองหรือติดต่อ {name} อย่างไร?", zh: "如何预订或联系 {name}？", ja: "{name}の予約・問い合わせ方法は？", ar: "كيف أحجز أو أتواصل مع {name}؟" },
  pf_book_a: { en: "Use the inquiry form on this page — it goes directly to {name} with 0% commission.", ko: "이 페이지의 문의 양식을 이용하세요 — {name}에 수수료 0%로 바로 전달됩니다.", th: "ใช้แบบฟอร์มสอบถามในหน้านี้ — ส่งตรงถึง {name} โดยไม่มีค่าคอมมิชชั่น", zh: "使用本页的咨询表单 — 0% 佣金直达 {name}。", ja: "このページの問い合わせフォームをご利用ください — 手数料0%で{name}に直接届きます。", ar: "استخدم نموذج الاستفسار في هذه الصفحة — يصل مباشرة إلى {name} بعمولة 0%." },
  pf_book_klook: { en: " You can also book through Klook for instant confirmation.", ko: " Klook을 통해 즉시 확정 예약도 가능합니다.", th: " หรือจองผ่าน Klook เพื่อยืนยันทันที", zh: " 也可通过 Klook 即时确认预订。", ja: " Klookからの即時確定予約も可能です。", ar: " يمكنك أيضًا الحجز عبر Klook لتأكيد فوري." },
  pf_book_phone: { en: " Or call {phone}.", ko: " 또는 {phone}로 전화하세요.", th: " หรือโทร {phone}", zh: " 或致电 {phone}。", ja: " または{phone}にお電話ください。", ar: " أو اتصل على {phone}." },
  pf_lang_q: { en: "What languages do they speak?", ko: "어떤 언어로 소통이 되나요?", th: "พูดภาษาอะไรได้บ้าง?", zh: "他们会说哪些语言？", ja: "対応言語は？", ar: "ما اللغات التي يتحدثونها؟" },
  pf_lang_a: { en: "Based on our research, {name} serves customers in {langs}.", ko: "조사에 따르면 {name}은(는) {langs}(으)로 응대합니다.", th: "จากข้อมูลของเรา {name} ให้บริการลูกค้าเป็นภาษา {langs}", zh: "根据我们的调研，{name} 可用 {langs} 接待顾客。", ja: "当社の調査では、{name}は{langs}で対応しています。", ar: "بناءً على بحثنا، يخدم {name} العملاء بـ {langs}." },
  pf_cost_q: { en: "How much does it cost?", ko: "비용은 얼마인가요?", th: "ราคาเท่าไหร่?", zh: "费用是多少？", ja: "料金はいくらですか？", ar: "كم التكلفة؟" },
  pf_cost_a: { en: "Typical price is {price} per {unit}. Prices may vary by season and service — confirm with the venue.", ko: "일반적인 가격은 {unit}당 {price}입니다. 시즌·서비스에 따라 달라질 수 있으니 업체에 확인하세요.", th: "ราคาทั่วไปอยู่ที่ {price} ต่อ {unit} ราคาอาจเปลี่ยนตามฤดูกาลและบริการ — โปรดยืนยันกับสถานที่", zh: "通常价格为每 {unit} {price}。价格可能因季节和服务而异 — 请向商家确认。", ja: "一般的な料金は{unit}あたり{price}です。季節やサービスにより変動する場合があります — 店舗にご確認ください。", ar: "السعر المعتاد هو {price} لكل {unit}. قد تختلف الأسعار حسب الموسم والخدمة — تأكد من المكان." },
  pf_pop_q: { en: "Is {name} popular / well-reviewed?", ko: "{name}은(는) 평이 좋은가요?", th: "{name} เป็นที่นิยม/รีวิวดีไหม?", zh: "{name} 受欢迎 / 评价好吗？", ja: "{name}は人気・高評価ですか？", ar: "هل {name} مشهور / حسن التقييم؟" },
  pf_pop_a: { en: "{name} has {count} Google reviews with an average rating of ★ {rating}/5.", ko: "{name}은(는) 구글 리뷰 {count}개, 평균 별점 ★ {rating}/5입니다.", th: "{name} มีรีวิว Google {count} รายการ คะแนนเฉลี่ย ★ {rating}/5", zh: "{name} 有 {count} 条 Google 评论，平均评分 ★ {rating}/5。", ja: "{name}はGoogleレビュー{count}件、平均評価★{rating}/5です。", ar: "لدى {name} {count} مراجعة على Google بمتوسط تقييم ★ {rating}/5." },
  pf_pop_partner: { en: " It's a verified partner on our platform.", ko: " 저희 플랫폼의 인증 파트너입니다.", th: " เป็นพาร์ทเนอร์ที่ยืนยันแล้วบนแพลตฟอร์มของเรา", zh: " 是我们平台的认证合作伙伴。", ja: " 当プラットフォームの認証パートナーです。", ar: " إنه شريك موثّق على منصتنا." },
  pf_beg_q: { en: "Is {name} good for beginners?", ko: "{name}은(는) 초보자에게 적합한가요?", th: "{name} เหมาะกับมือใหม่ไหม?", zh: "{name} 适合初学者吗？", ja: "{name}は初心者向けですか？", ar: "هل {name} مناسب للمبتدئين؟" },
  pf_beg_a: { en: "Yes — {name} is rated beginner-friendly. Expect welcoming staff, intro sessions, and equipment provided for first-time visitors.", ko: "네 — {name}은(는) 초보 친화로 평가됩니다. 친절한 직원, 입문 세션, 첫 방문자용 장비 제공을 기대할 수 있습니다.", th: "ใช่ — {name} ได้รับการจัดว่าเหมาะกับมือใหม่ มีพนักงานที่เป็นมิตร คลาสเริ่มต้น และอุปกรณ์สำหรับผู้มาครั้งแรก", zh: "是的 — {name} 被评为适合初学者。会有热情的工作人员、入门课程，并为首次到访者提供器材。", ja: "はい — {name}は初心者向けと評価されています。親切なスタッフ、入門セッション、初回利用者向けの用具が期待できます。", ar: "نعم — {name} مصنّف كملائم للمبتدئين. توقّع موظفين ودودين وجلسات تعريفية ومعدات للزوار الجدد." },
  pf_24h_q: { en: "Is {name} open 24 hours?", ko: "{name}은(는) 24시간 운영하나요?", th: "{name} เปิด 24 ชั่วโมงไหม?", zh: "{name} 24 小时营业吗？", ja: "{name}は24時間営業ですか？", ar: "هل {name} مفتوح 24 ساعة؟" },
  pf_24h_a: { en: "Yes, {name} operates 24 hours. Confirm specific service hours by inquiry.", ko: "네, {name}은(는) 24시간 운영합니다. 구체적인 서비스 시간은 문의로 확인하세요.", th: "ใช่ {name} เปิดบริการ 24 ชั่วโมง โปรดสอบถามเวลาบริการเฉพาะ", zh: "是的，{name} 24 小时营业。具体服务时间请咨询确认。", ja: "はい、{name}は24時間営業です。具体的なサービス時間はお問い合わせください。", ar: "نعم، يعمل {name} على مدار 24 ساعة. أكّد ساعات الخدمة المحددة بالاستفسار." },

  // place-detail Schema.org description (LocalBusiness JSON-LD)
  schema_place_desc: { en: "{niche} in {city}, Thailand. Trust Score {score}/100.", ko: "{city}, 태국의 {niche}. 신뢰 점수 {score}/100.", th: "{niche}ใน{city} ประเทศไทย คะแนนความน่าเชื่อถือ {score}/100", zh: "泰国{city}的{niche}。信任分数 {score}/100。", ja: "タイ・{city}の{niche}。信頼スコア {score}/100。", ar: "{niche} في {city}، تايلاند. درجة الثقة {score}/100." },

  // ── place-detail section headings & labels (visible page structure).
  // Continuation of the t()-template i18n pass; {name}/{niche}/{place} via tf().
  toc_services: { en: "Services", ko: "서비스", th: "บริการ", zh: "服务", ja: "サービス", ar: "الخدمات" },
  toc_location: { en: "Location", ko: "위치", th: "ที่ตั้ง", zh: "位置", ja: "場所", ar: "الموقع" },
  toc_book: { en: "Book", ko: "예약", th: "จอง", zh: "预订", ja: "予約", ar: "احجز" },
  trust_crosschecked: { en: "Cross-checked across:", ko: "교차 검증 소스:", th: "ตรวจสอบข้ามจาก:", zh: "交叉验证来源：", ja: "クロスチェック元：", ar: "تم التحقق عبر:" },
  verified_partner: { en: "Verified Partner", ko: "인증 파트너", th: "พาร์ทเนอร์ที่ยืนยันแล้ว", zh: "认证合作伙伴", ja: "認証パートナー", ar: "شريك موثّق" },
  ra_title: { en: "Review Activity", ko: "리뷰 활동", th: "ความเคลื่อนไหวรีวิว", zh: "评论活跃度", ja: "レビュー動向", ar: "نشاط المراجعات" },
  ra_30d: { en: "Last 30 days", ko: "최근 30일", th: "30 วันล่าสุด", zh: "最近 30 天", ja: "過去30日", ar: "آخر 30 يومًا" },
  ra_90d: { en: "Last 90 days", ko: "최근 90일", th: "90 วันล่าสุด", zh: "最近 90 天", ja: "過去90日", ar: "آخر 90 يومًا" },
  ra_year: { en: "This year", ko: "올해", th: "ปีนี้", zh: "今年", ja: "今年", ar: "هذا العام" },
  ra_lastreviewed: { en: "Last reviewed {ago}", ko: "마지막 리뷰 {ago}", th: "รีวิวล่าสุด {ago}", zh: "最近评论 {ago}", ja: "最終レビュー {ago}", ar: "آخر مراجعة {ago}" },
  rate_exceptional: { en: "Exceptional", ko: "최고", th: "ยอดเยี่ยมมาก", zh: "卓越", ja: "極めて良い", ar: "استثنائي" },
  rate_excellent: { en: "Excellent", ko: "훌륭함", th: "ยอดเยี่ยม", zh: "优秀", ja: "非常に良い", ar: "ممتاز" },
  rate_verygood: { en: "Very good", ko: "매우 좋음", th: "ดีมาก", zh: "很好", ja: "とても良い", ar: "جيد جدًا" },
  rate_good: { en: "Good", ko: "좋음", th: "ดี", zh: "好", ja: "良い", ar: "جيد" },
  review_anon: { en: "Anonymous", ko: "익명", th: "ไม่ระบุชื่อ", zh: "匿名", ja: "匿名", ar: "مجهول" },
  book_direct_title: { en: "Book directly with {name}", ko: "{name}에 직접 예약", th: "จองโดยตรงกับ {name}", zh: "直接预订 {name}", ja: "{name}に直接予約", ar: "احجز مباشرة مع {name}" },
  book_direct_sub: { en: "No commission · No booking platform markup · Pay at the venue", ko: "수수료 없음 · 예약 플랫폼 마크업 없음 · 현장 결제", th: "ไม่มีค่าคอมมิชชั่น · ไม่มีส่วนต่างแพลตฟอร์ม · จ่ายที่ร้าน", zh: "无佣金 · 无平台加价 · 到店付款", ja: "手数料なし · プラットフォーム上乗せなし · 現地払い", ar: "بدون عمولة · بدون رسوم المنصة · ادفع في المكان" },
  fee_0: { en: "0% fee", ko: "수수료 0%", th: "ค่าธรรมเนียม 0%", zh: "0% 费用", ja: "手数料0%", ar: "رسوم 0%" },
  reply_in: { en: "Replies in ~{t}", ko: "~{t} 내 답변", th: "ตอบใน ~{t}", zh: "约 {t} 内回复", ja: "~{t}で返信", ar: "يرد خلال ~{t}" },
  or_book_klook: { en: "Or book via Klook", ko: "또는 Klook으로 예약", th: "หรือจองผ่าน Klook", zh: "或通过 Klook 预订", ja: "またはKlookで予約", ar: "أو احجز عبر Klook" },
  services_pricing: { en: "Services & pricing", ko: "서비스 & 가격", th: "บริการและราคา", zh: "服务与价格", ja: "サービスと料金", ar: "الخدمات والأسعار" },
  msg_directly: { en: "Message {name} directly", ko: "{name}에 직접 메시지", th: "ส่งข้อความถึง {name} โดยตรง", zh: "直接给 {name} 发消息", ja: "{name}に直接メッセージ", ar: "راسل {name} مباشرة" },
  line_scan_title: { en: "Scan to chat on LINE", ko: "스캔하여 LINE으로 대화", th: "สแกนเพื่อแชทบน LINE", zh: "扫码在 LINE 上聊天", ja: "スキャンしてLINEでチャット", ar: "امسح للدردشة على LINE" },
  line_scan_sub: { en: "Open LINE camera → scan this QR → book directly", ko: "LINE 카메라 열기 → QR 스캔 → 바로 예약", th: "เปิดกล้อง LINE → สแกน QR นี้ → จองโดยตรง", zh: "打开 LINE 相机 → 扫描此二维码 → 直接预订", ja: "LINEカメラを開く → このQRをスキャン → 直接予約", ar: "افتح كاميرا LINE ← امسح رمز QR ← احجز مباشرة" },
  send_inquiry_title: { en: "Send inquiry directly", ko: "직접 문의 보내기", th: "ส่งคำถามโดยตรง", zh: "直接发送咨询", ja: "直接問い合わせを送信", ar: "أرسل استفسارًا مباشرة" },
  inquiry_goes_to: { en: "Goes straight to {name}. No booking platform markup.", ko: "{name}에 바로 전달됩니다. 예약 플랫폼 마크업 없음.", th: "ส่งตรงถึง {name} ไม่มีส่วนต่างแพลตฟอร์ม", zh: "直达 {name}。无平台加价。", ja: "{name}に直接届きます。プラットフォーム上乗せなし。", ar: "يصل مباشرة إلى {name}. بدون رسوم المنصة." },
  or_book_partner: { en: "Or book through a partner platform", ko: "또는 파트너 플랫폼으로 예약", th: "หรือจองผ่านแพลตฟอร์มพาร์ทเนอร์", zh: "或通过合作平台预订", ja: "またはパートナープラットフォームで予約", ar: "أو احجز عبر منصة شريكة" },
  own_q: { en: "Own {name}?", ko: "{name} 사장님이신가요?", th: "เป็นเจ้าของ {name}?", zh: "您是 {name} 的店主吗？", ja: "{name}のオーナーですか？", ar: "هل تملك {name}؟" },
  claim_blurb: { en: "Claim this listing to manage hours, descriptions, photos, and reach more customers.", ko: "이 리스팅을 인증하고 운영시간·설명·사진을 관리하며 더 많은 고객에게 도달하세요.", th: "ยืนยันรายการนี้เพื่อจัดการเวลาทำการ คำอธิบาย รูปภาพ และเข้าถึงลูกค้ามากขึ้น", zh: "认领此商家以管理营业时间、简介、照片并触达更多顾客。", ja: "このリスティングを申請して営業時間・説明・写真を管理し、より多くの顧客にリーチしましょう。", ar: "طالب بهذا الإدراج لإدارة المواعيد والوصف والصور والوصول إلى المزيد من العملاء." },
  claim_cta: { en: "Claim this listing →", ko: "이 리스팅 인증하기 →", th: "ยืนยันรายการนี้ →", zh: "认领此商家 →", ja: "このリスティングを申請 →", ar: "طالب بهذا الإدراج ←" },
  sec_korean_reviews: { en: "Korean reviews", ko: "한국어 후기", th: "รีวิวภาษาเกาหลี", zh: "韩语评论", ja: "韓国語レビュー", ar: "مراجعات كورية" },
  sec_thai_disc: { en: "Local Thai discussions", ko: "태국 현지 토론", th: "การสนทนาของคนไทย", zh: "泰国本地讨论", ja: "タイ現地の議論", ar: "نقاشات تايلاندية محلية" },
  sec_videos_about: { en: "Videos about {name}", ko: "{name} 관련 영상", th: "วิดีโอเกี่ยวกับ {name}", zh: "关于 {name} 的视频", ja: "{name}に関する動画", ar: "فيديوهات عن {name}" },
  sec_featured_yt: { en: "Featured on YouTube", ko: "유튜브에 소개됨", th: "ปรากฏบน YouTube", zh: "YouTube 精选", ja: "YouTubeで紹介", ar: "ظهر على YouTube" },
  more_niche_in: { en: "More {niche} in {place}", ko: "{place}의 {niche} 더 보기", th: "{niche}เพิ่มเติมใน{place}", zh: "{place}更多{niche}", ja: "{place}の{niche}をもっと見る", ar: "المزيد من {niche} في {place}" },
  country_thailand: { en: "Thailand", ko: "태국", th: "ประเทศไทย", zh: "泰国", ja: "タイ", ar: "تايلاند" },

  back_to_niche: { en: "← Back to {niche}", ko: "← {niche}(으)로 돌아가기", th: "← กลับไปที่{niche}", zh: "← 返回{niche}", ja: "← {niche}に戻る", ar: "← العودة إلى {niche}" },

  // FAQ index page
  faq_hero_title: { en: "Thailand wellness FAQ", ko: "태국 웰니스 FAQ", th: "คำถามที่พบบ่อยเกี่ยวกับเวลเนสในไทย", zh: "泰国康养常见问题", ja: "タイ・ウェルネスFAQ", ar: "الأسئلة الشائعة عن العافية في تايلاند" },
  faq_hero_sub: { en: "Honest answers to the most common questions about yoga retreats, muay thai camps, spa pricing, diving, and digital nomad life in Thailand.", ko: "요가 리트릿, 무에타이 캠프, 스파 가격, 다이빙, 디지털 노마드 생활까지 — 태국에 대한 가장 흔한 질문에 솔직하게 답합니다.", th: "คำตอบตรงไปตรงมาสำหรับคำถามยอดนิยมเกี่ยวกับโยคะรีทรีต ค่ายมวยไทย ราคาสปา การดำน้ำ และชีวิตดิจิทัลโนแมดในไทย", zh: "关于瑜伽静修、泰拳训练营、水疗价格、潜水以及泰国数字游民生活最常见问题的诚实解答。", ja: "ヨガリトリート、ムエタイキャンプ、スパ料金、ダイビング、タイでのデジタルノマド生活について、よくある質問に正直にお答えします。", ar: "إجابات صادقة عن أكثر الأسئلة شيوعًا حول منتجعات اليوغا ومعسكرات الملاكمة التايلاندية وأسعار السبا والغوص وحياة الرحّل الرقميين في تايلاند." },
  faq_curated_badge: { en: "{n} curated questions · cross-checked against 6 sources", ko: "엄선된 질문 {n}개 · 6개 소스 교차 검증", th: "{n} คำถามคัดสรร · ตรวจสอบข้ามจาก 6 แหล่ง", zh: "{n} 个精选问题 · 6 个来源交叉验证", ja: "厳選された{n}の質問 · 6つの情報源でクロスチェック", ar: "{n} سؤالًا مختارًا · تم التحقق عبر 6 مصادر" },
  faq_topic_general: { en: "General", ko: "일반", th: "ทั่วไป", zh: "综合", ja: "一般", ar: "عام" },
  faq_index_title: { en: "FAQ — Thailand yoga, spa, muay thai, diving", ko: "FAQ — 태국 요가·스파·무에타이·다이빙", th: "คำถามที่พบบ่อย — โยคะ สปา มวยไทย ดำน้ำ ในไทย", zh: "常见问题 — 泰国瑜伽、水疗、泰拳、潜水", ja: "FAQ — タイのヨガ・スパ・ムエタイ・ダイビング", ar: "الأسئلة الشائعة — اليوغا والسبا والملاكمة التايلاندية والغوص في تايلاند" },
  faq_index_desc: { en: "Common questions about Thailand wellness, spa, muay thai, yoga retreats, diving certification, and digital nomad coworking. Real data from {n} curated entries.", ko: "태국 웰니스, 스파, 무에타이, 요가 리트릿, 다이빙 자격증, 디지털 노마드 코워킹에 대한 흔한 질문들. 엄선된 {n}개 항목의 실제 데이터.", th: "คำถามทั่วไปเกี่ยวกับเวลเนส สปา มวยไทย โยคะรีทรีต ใบรับรองดำน้ำ และโคเวิร์กกิ้งสำหรับดิจิทัลโนแมดในไทย ข้อมูลจริงจาก {n} รายการคัดสรร", zh: "关于泰国康养、水疗、泰拳、瑜伽静修、潜水认证及数字游民共享办公的常见问题。来自 {n} 个精选条目的真实数据。", ja: "タイのウェルネス、スパ、ムエタイ、ヨガリトリート、ダイビング資格、デジタルノマド向けコワーキングに関するよくある質問。厳選された{n}件の実データ。", ar: "أسئلة شائعة حول العافية والسبا والملاكمة التايلاندية ومنتجعات اليوغا وشهادات الغوص ومساحات العمل المشتركة للرحّل الرقميين في تايلاند. بيانات حقيقية من {n} مدخلًا مختارًا." },

  // ── city hub page (/[lang]/city/[slug]). en-only here; ko/th/zh/ja/ar/id/vi
  // are filled by scripts/translate_ui.mjs into the ui_i18n.json sidecar.
  // Placeholders ({city},{n},{cats},{list},{name},{niche},{year},{years}) are
  // preserved by the translator.
  city_crumb: { en: "Cities" },
  city_title: { en: "{city}, Thailand" },
  city_badge_verified: { en: "{n} verified places" },
  city_badge_korean: { en: "{n} Korean-friendly" },
  city_badge_cats: { en: "{n} categories" },
  city_map_title: { en: "Map of {city}" },
  city_map_count: { en: "{n} mapped venues" },
  city_browse_title: { en: "Browse {city} by category" },
  city_browse_sub: { en: "{n} categories with verified places · Tap a card to see the ranked top-10 guide." },
  city_toppicks_title: { en: "Top picks in {city}" },
  city_toppicks_sub: { en: "Highest cross-source trust scores across all categories." },
  city_faq_title: { en: "FAQ — {city}" },
  cf_count_q: { en: "How many verified places are listed in {city}?" },
  cf_count_a: { en: "Verified Thai lists {n} cross-checked places in {city}, spanning {cats} categories. Each is scored independently across 6 sources (Google, Reddit, Naver, Pantip, YouTube, official sites)." },
  cf_korean_q: { en: "Are there Korean-friendly options in {city}?" },
  cf_korean_a: { en: "{n} of the {total} {city} listings have Korean-language reviews or Korean-speaking staff signals — surfaced from Naver and YouTube mentions." },
  cf_beginner_q: { en: "Are any places in {city} beginner-friendly?" },
  cf_beginner_a: { en: "{n} {city} listings are flagged as beginner-friendly across our reviews aggregation — see the beginner badge on individual listings." },
  cf_best_q: { en: "What's the best category in {city}?" },
  cf_best_a: { en: "{city} is densest in {list}. See per-category guides below for ranked top-10 lists." },
  cf_paid_q: { en: "Does Verified Thai accept paid placement in {city}?" },
  cf_paid_a: { en: "No. Listings are ranked purely by an independent Trust Score combining Google reviews, Reddit, Naver, Pantip, YouTube mentions, and official website signals. We accept zero payment to rank a business." },
  cf_estab_q: { en: "How many venues in {city} have been operating 5+ years?" },
  cf_estab_a: { en: "{n} of the {total} {city} venues we list have an archive.org footprint going back at least 5 years{vet}. Long-tenure is one of the few signals that can't be faked." },
  cf_estab_vet: { en: " — {n} of those go back 10+ years" },
  cf_oldest_q: { en: "What's the oldest venue in {city} on Verified Thai?" },
  cf_oldest_a: { en: "{name} ({niche}) has the earliest archive.org capture among {city} listings — first archived in {year}, over {years} years ago." },
  cf_active_q: { en: "Which {city} venues are actually still open?" },
  cf_active_a: { en: "{n} of the {total} {city} venues had at least one Google review in the last 90 days{recent} — the strongest \"still trading right now\" signal we surface from public data." },
  cf_active_recent: { en: ", {n} of those within the last 30 days" },
  cf_toptrust_q: { en: "What are the highest-trust places in {city} right now?" },
  cf_toptrust_a: { en: "By our cross-source trust score, the top three in {city} are: {list}. Rankings update with each scrape — no paid placement." },
  city_other_cities: { en: "Other cities in Thailand" },
  city_compare: { en: "Compare:" },
  city_vs: { en: "{a} vs {b}" },
  city_meta_title: { en: "{city}, Thailand — {n} Verified Places" },

  // ── guide page (/[lang]/guide/[slug]) — city × niche top-10. en-only here;
  // translate_ui fills the rest. Placeholders preserved.
  g_title: { en: "Top {n} {niche} in {city}" },
  g_sub: { en: "Independently scored across 6 sources. No paid placement. Updated continuously." },
  g_summary: { en: "Quick summary" },
  g_card_verified: { en: "Verified places" },
  g_card_price: { en: "Price (THB)" },
  g_of_top: { en: "of top {n}" },
  g_to_price: { en: "to ฿{n}" },
  g_list_title: { en: "The list — top {n} ranked by Trust Score" },
  g_list_sub: { en: "Trust Score combines Google reviews, Reddit / Pantip mentions, Naver blog posts, YouTube videos, and official website signals." },
  g_related: { en: "Related guides" },
  g_back: { en: "← All {niche} in Thailand" },
  g_meta_title: { en: "Top {n} {niche} in {city}, Thailand" },
  g_meta_desc: { en: "Independent guide to the top {niche} in {city}, Thailand. Cross-checked across 6 sources. No paid promotion. Real Korean / Thai / English reviews." },
  gf_count_q: { en: "How many verified {niche} places are there in {city}?" },
  gf_count_a: { en: "Verified Thai lists {all} {niche} places across Thailand and {n} specifically in {city}, each cross-checked across Google, Reddit, Naver, Pantip, YouTube, and official websites." },
  gf_price_q: { en: "How much does {niche} cost in {city}?" },
  gf_price_a: { en: "Based on our data, prices range from about ฿{lo} to ฿{hi}. Exact pricing varies by studio — check each listing for current rates." },
  gf_korean_q: { en: "Are there Korean-friendly {niche} options in {city}?" },
  gf_korean_a: { en: "Yes — {n} of our top {top} {city} {niche} listings have Korean-language reviews or Korean-speaking staff signals." },
  gf_beginner_q: { en: "Are there beginner-friendly options?" },
  gf_beginner_a: { en: "{n} of the top {top} {city} {niche} places are flagged as beginner-friendly in our reviews aggregation." },
  gf_24h_q: { en: "Are any places open 24 hours?" },
  gf_24h_a: { en: "Yes — at least one of our top {city} {niche} listings operates 24 hours. Check individual listing hours for confirmation." },
  gf_paid_q: { en: "Does Verified Thai accept paid placements?" },
  gf_paid_a: { en: "No. Listings are ranked purely by our independent Trust Score — a composite of Google reviews, Reddit, Naver, Pantip, YouTube mentions, and official website verification." },

  // localized language names (for the "languages spoken" FAQ list)
  langname_en: { en: "English", ko: "영어", th: "อังกฤษ", zh: "英语", ja: "英語", ar: "الإنجليزية" },
  langname_ko: { en: "Korean", ko: "한국어", th: "เกาหลี", zh: "韩语", ja: "韓国語", ar: "الكورية" },
  langname_th: { en: "Thai", ko: "태국어", th: "ไทย", zh: "泰语", ja: "タイ語", ar: "التايلاندية" },
  langname_zh: { en: "Chinese", ko: "중국어", th: "จีน", zh: "中文", ja: "中国語", ar: "الصينية" },
  langname_ja: { en: "Japanese", ko: "일본어", th: "ญี่ปุ่น", zh: "日语", ja: "日本語", ar: "اليابانية" },
  langname_ar: { en: "Arabic", ko: "아랍어", th: "อาหรับ", zh: "阿拉伯语", ja: "アラビア語", ar: "العربية" },
} as const;

export function t<K extends keyof typeof T>(key: K, lang: Lang): string {
  const node = T[key] as Record<string, string>;
  return node[lang] ?? UI_I18N[key as string]?.[lang] ?? node[DEFAULT_LANG];
}

// Translate + fill {var} placeholders in one step. Shared by highlights,
// place FAQs, and anywhere a localized string carries dynamic values.
export function tf<K extends keyof typeof T>(
  key: K,
  lang: Lang,
  vars: Record<string, string | number>,
): string {
  let s = t(key, lang);
  for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v));
  return s;
}
